title: Phantom's Blog
author: PhantomEnderium
description: Games, Coding, life events, and other daily things!
markdown: kramdown
permalink: /posts/:year/:month/:day/:title/
baseurl: /blog

excerpt_separator: <!--more-->